### ISSUE TITLE
Installation error. 

### ISSUE THREAD

**Issue by samburu** [natcap/rangeland_production#23]
```
make env
make: powershell.exe: Command not found
make: powershell.exe: Command not found
make: powershell.exe: Command not found
python -m venv --system-site-packages env
make: powershell.exe: Command not found
Makefile:101: recipe for target 'env' failed
make: *** [env] Error 127
```
Ubuntu version
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

```

**Comment by vakowal** [comment]
Hi @samburu , sorry the makefile didn't work for you. I would suggest building your virtual environment using whatever environment manager works for you, and then installing the required packages found in requirements.txt and requirements-dev.txt.  Of course, if you just want to run RPM, you can download the Python wheel package from the releases section and install it on your system using `pip`.

**Comment by samburu** [comment]
Thanks a ton @vakowal.

**Comment by samburu** [comment]
Hi @vakowal,

Is it possible to add sample data to the repo to test the installation?

**Comment by vakowal** [comment]
Hi @samburu , yes there are sample data distributed with each release. Head over to https://github.com/natcap/rangeland_production/releases/latest and find the sample inputs in a zip file there.

**Comment by samburu** [comment]
Thanks a lot @vakowal.

**Comment by samburu** [comment]
Hi @vakowal.
I'm trying to run the RPM but i"m only getting output for the first month. The diet sufficiency and standing biomass geotiff for the first month are empty.  I was i wondering if with information you can help be debug? 

Thanks a ton

**Comment by vakowal** [comment]
Hi @samburu , no problem! could you please send me the logfile from your model run? It is a text file saved in your workspace and may be called "Rangeland-Production-Model-log-...txt" or "InVEST-log....txt"

**Comment by samburu** [comment]
Thanks @vakowal for the quick reply.

i"m running the model is by importing `execute` from `forage` 

The output folder has the following subfolder 
![image](https://user-images.githubusercontent.com/5626929/90901767-1d28b380-e3d4-11ea-9fa8-07ca35cbe3dc.png)

**Comment by samburu** [comment]
Here is the traceback
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/opt/conda/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/src/app/models/livestock_model/tasks.py", line 167, in run
    execute(args)
  File "/usr/src/app/models/livestock_model/forage.py", line 1292, in execute
    month_reg,
  File "/usr/src/app/models/livestock_model/forage.py", line 17200, in _estimate_animal_density
    temp_val_dict["biomass_potential_normalized"],
  File "/usr/src/app/models/livestock_model/forage.py", line 16902, in normalize_within_grazing_areas
    [(fid, float(table["min"])) for fid, table in zonal_stats.items()]
  File "/usr/src/app/models/livestock_model/forage.py", line 16902, in <listcomp>
    [(fid, float(table["min"])) for fid, table in zonal_stats.items()]
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by vakowal** [comment]
Hi @samburu , looks like the problem has to do with reading the shapefile containing animal grazing areas. I would check the rasters in your aligned inputs and make sure that they have valid values inside the features of the animal grazing areas shapefile. It's possible that when the inputs were aligned and resampled, some areas were left out.
If you'd like to send a copy of your args dictionary that you are supplying as input to `execute`, I can also check to see if the inputs are formatted correctly. This step is sometimes a bit of a pain to get right.

**Comment by samburu** [comment]
Thanks @vakowal  a ton for the assistance
Below is agrs dict
```
args = {
        'workspace_dir': '/home/pmburu/repo/rangeland_production/src/rangeland_production/output_new',
        'starting_month': 1,
        'starting_year':2015,
        'n_months':12,
        'aoi_path':'/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/tasks/models.livestock_model.tasks.GeographyToShape_admin2_South_Sudan___type____Featur_32ca0f3c57.pickle/models.livestock_model.tasks.GeographyToShape_admin2_South_Sudan___type____Featur_32ca0f3c57.shp',
        'management_threshold':0.2,
        'proportion_legume_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/pasture_legume_bb326aa81c.tif',
        'bulk_density_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/models.livestock_model.data_pre.MaskSoilData_admin2_South_Sudan___type____Featur_32ca0f3c57_bulk.tif',
        'ph_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/models.livestock_model.data_pre.MaskSoilData_admin2_South_Sudan___type____Featur_32ca0f3c57_ph.tif',
        'clay_proportion_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/models.livestock_model.data_pre.MaskSoilData_admin2_South_Sudan___type____Featur_32ca0f3c57_clay.tif',
        'silt_proportion_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/models.livestock_model.data_pre.MaskSoilData_admin2_South_Sudan___type____Featur_32ca0f3c57_silt.tif',
        'sand_proportion_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/models.livestock_model.data_pre.MaskSoilData_admin2_South_Sudan___type____Featur_32ca0f3c57_sand.tif',
        'monthly_precip_path_pattern': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/maskedRainfall_32ca0f3c57.pickle/chirps-v2.0.<year>.<month>.tif',
        'min_temp_path_pattern': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/mask_min_temp_32ca0f3c57.pickle/min_temperature_<month>.tif',
        'max_temp_path_pattern': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/mask_max_temp_32ca0f3c57.pickle/max_temperature_<month>.tif',
        'monthly_vi_path_pattern': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/masked_ndvi_32ca0f3c57.pickle/ndvi_<year>_<month>.tif',
        'site_param_table': '/home/pmburu/Downloads/site_parameters.csv',
        'site_param_spatial_index_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/data_pre/site_index_5416b3cf38.tif',
        'veg_trait_path': '/home/pmburu/Downloads/pft_trait.csv',
        'veg_spatial_composition_path_pattern': '/home/pmburu/repo/darpa/output/intermediate_targets/models.livestock_model.data_pre.MaskPFTData_admin2_South_Sudan___type____Featur_5416b3cf38/pft<PFT>.tif',
        'animal_trait_path': '/home/pmburu/Downloads/eth_all_animal_trait.csv',
        'animal_grazing_areas_path': '/home/pmburu/repo/darpa/output/intermediate_targets/models/livestock_model/tasks/models.livestock_model.tasks.ExtractGrazingArea__99914b932b.pickle/eth_animal_location.shp',
        'site_initial_table': '/home/pmburu/Downloads/site_initial_table (1).csv',
        'pft_initial_table': '/home/pmburu/Downloads/pft_initial_table.csv',
        }
```

**Comment by samburu** [comment]
Attached below is the animal location shapefile and animal trait table
[animal_shapefile.zip](https://github.com/natcap/rangeland_production/files/5119350/animal_shapefile.zip)
[eth_all_animal_trait.xlsx](https://github.com/natcap/rangeland_production/files/5119354/eth_all_animal_trait.xlsx)

**Comment by samburu** [comment]
The biomass potential raster is empty when the model fail. 
```
(Pdb) src
<open DatasetReader name='output/intermediate_targets/models/livestock_model/tasks/models.livestock_model.tasks.RunRangeLandProductionModel_admin2_South_Sudan_0_0_bb326aa81c.pickle-luigi-tmp-5400459004/temporary_files/tmp7051c8gz/biomass_potential.tif' mode='r'>
(Pdb) arr = src.read(1)
(Pdb) arr
array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ...,
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]], dtype=float32)
(Pdb) arr.max()
-1.0
(Pdb) arr.min()
-1.0
(Pdb) zonal_stats
{0: {'min': None, 'max': None, 'count': 0, 'nodata_count': 3383, 'sum': 0.0}, 1: {'min': None, 'max': None, 'count': 0, 'nodata_count': 1004, 'sum': 0.0}, 2: {'min': None, 'max': None, 'count': 0, 'nodata_count': 12, 'sum': 0.0}, 3: {'min': None, 'max': None, 'count': 0, 'nodata_count': 34, 'sum': 0.0}, 4: {'min': None, 'max': None, 'count': 0, 'nodata_count': 10495, 'sum': 0.0}, 5: {'min': None, 'max': None, 'count': 0, 'nodata_count': 10254, 'sum': 0.0}, 6: {'min': None, 'max': None, 'count': 0, 'nodata_count': 1664, 'sum': 0.0}, 7: {'min': None, 'max': None, 'count': 0, 'nodata_count': 4939, 'sum': 0.0}, 8: {'min': None, 'max': None, 'count': 0, 'nodata_count': 3111, 'sum': 0.0}, 9: {'min': None, 'max': None, 'count': 0, 'nodata_count': 1820, 'sum': 0.0}}

**Comment by samburu** [comment]
@vakowal i'm not sure if this help but the grid for energy_maintenance, daily_intake_agliv_<pft> and energy_intake are empty.

**Comment by samburu** [comment]
Missing values in SRW  column (animal trait csv file) was the cause of the problem.  Thanks very much @vakowal  for the help.

**Comment by vakowal** [comment]
Hi @samburu very glad you got it sorted out without my help at all!

**Comment by samburu** [comment]
You did suggest that i look into animal data which was very helpful. 
What would happen if temperature data (max and min) had both year and month?

**Comment by vakowal** [comment]
Hi @samburu do you mean that you would supply temperature data for each month of the simulation, rather than just for each month of the year? unfortunately the model is set up to only use yearly average min/max temperature for each month, so if you supplied a path pattern similar to the precipitation or NDVI patterns, including "<year>", that pattern would not be recognized. You can see how the model identifies what temperature inputs to use around line 712 in forage.py.
