### ISSUE TITLE
Logger fails with permission error when running from GUI

### ISSUE THREAD

**Issue by vakowal** [natcap/rangeland_production#43]
When running RPM on my machine after building the Windows installer, I get an error:
2020-12-22 10:47:44,428 execution.run(78) ERROR Target <function InVESTModel.execute_model.<locals>._logged_target at 0x124095D0> failed with exception
Traceback (most recent call last):
File "src\rangeland_production\ui\execution.py", line 68, in run
File "src\rangeland_production\ui\model.py", line 1631, in _logged_target
File "contextlib.py", line 112, in __enter__
File "src\rangeland_production\utils.py", line 111, in prepare_workspace
File "contextlib.py", line 112, in __enter__
File "src\rangeland_production\utils.py", line 184, in log_to_file
File "logging\__init__.py", line 1087, in __init__
File "logging\__init__.py", line 1116, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ginge\\Desktop\\RPM_TEST\\Rangeland-Production-Model-log-2020-12-22--10_47_44.txt'
2020-12-22 10:47:44,432 execution.run(83) INFO Execution finished

I only get this when using the gui, not when running from Python script importing the v0.2.0 package.

**Comment by vakowal** [comment]
Doug didn't get this error when installing RPM 0.2.0 and running on his computer.

Also, the location of the folder specified as workspace relative to the install location of RPM itself matters: if I run RPM and set the workspace to be a folder inside the root directory where RPM is installed, I do not get this error.  But if I install RPM inside the root directory (C:/) and set the workspace to be a folder inside my user directory (C:/Users/ginge/), I get this error.

**Comment by vakowal** [comment]
This is an issue specific to my local machine. Closing for now until it crops up for someone else.
